name: MAUI iOS Build

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: macos-latest


    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x


    - name: Install MAUI
      run: |
        dotnet workload install maui


    - name: Restore
      run: |
        dotnet restore

    - name: Build IPA
      run: |
       dotnet publish -f net9.0-ios -c Release \
         -p:ArchiveOnBuild=true \
         -p:RuntimeIdentifier=ios-arm64 \
         -p:CodesignKey="iPhone Distribution" \
         -p:CodesignProvision="YourProfileName"

    - name: Build iOS
      run: |
        dotnet build \
        -f net8.0-ios \
        -c Release

